<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.taqueriaalan</groupId>
    <artifactId>taqueria-alan-seminario</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Taqueria Alan Seminario</name>
    <description>Proyecto Spring Boot basado en microservicios (auth, catalogo, pedidos, pagos)</description>

    <properties>
        <java.version>21</java.version>
    </properties>

    <modules>
        <module>src/auth-service</module>
        <module>src/catalogo-service</module>
        <module>src/pedidos-service</module>
        <module>src/pagos-service</module>
    </modules>
</project>
