spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      ssl:
        enabled: ${REDIS_SSL:true}

app:
  security:
    enabled: ${SECURITY_ENABLED:true}
